export const mockPlayers = [
  {
    id: 1,
    playerID: "P001",
    teamID: "T001",
    name: "Luka Dončić",
    team: "Dallas Mavericks",
    position: "PG",
    image: "/basketball-player-portrait.png",
    regularSeason: {
      gamesPlayed: 70,
      minutes: 37.5,
      points: 33.9,
      assists: 9.8,
      rebounds: 9.2,
      offensiveReb: 1.2,
      defensiveReb: 8.0,
      steals: 1.4,
      blocks: 0.5,
      turnovers: 4.1,
      fieldGoalsMade: 11.9,
      fieldGoalsAttempted: 24.3,
      fieldGoalPct: 48.7,
      threePointsMade: 3.6,
      threePointsAttempted: 10.2,
      threePointPct: 35.3,
      freeThrowsMade: 6.5,
      freeThrowsAttempted: 8.1,
      freeThrowPct: 80.2,
      personalFouls: 2.1,
      plusMinus: 5.2,
      efficiency: 31.2,
    },
    playoffs: {
      gamesPlayed: 22,
      minutes: 40.1,
      points: 28.8,
      assists: 9.6,
      rebounds: 9.5,
      offensiveReb: 1.1,
      defensiveReb: 8.4,
      steals: 1.2,
      blocks: 0.6,
      turnovers: 3.8,
      fieldGoalsMade: 10.2,
      fieldGoalsAttempted: 22.1,
      fieldGoalPct: 46.1,
      threePointsMade: 3.1,
      threePointsAttempted: 9.5,
      threePointPct: 32.6,
      freeThrowsMade: 5.3,
      freeThrowsAttempted: 6.8,
      freeThrowPct: 77.9,
      personalFouls: 2.3,
      plusMinus: 3.1,
      efficiency: 28.9,
    },
  },
  {
    id: 2,
    playerID: "P002",
    teamID: "T002",
    name: "Giannis Antetokounmpo",
    team: "Milwaukee Bucks",
    position: "PF",
    image: "/basketball-player-portrait.png",
    regularSeason: {
      gamesPlayed: 73,
      minutes: 35.2,
      points: 30.4,
      assists: 6.5,
      rebounds: 11.5,
      offensiveReb: 2.9,
      defensiveReb: 8.6,
      steals: 1.2,
      blocks: 1.1,
      turnovers: 3.4,
      fieldGoalsMade: 11.5,
      fieldGoalsAttempted: 19.6,
      fieldGoalPct: 58.7,
      threePointsMade: 0.6,
      threePointsAttempted: 2.3,
      threePointPct: 26.1,
      freeThrowsMade: 6.8,
      freeThrowsAttempted: 10.7,
      freeThrowPct: 63.5,
      personalFouls: 3.1,
      plusMinus: 6.8,
      efficiency: 32.1,
    },
    playoffs: {
      gamesPlayed: 6,
      minutes: 36.8,
      points: 35.2,
      assists: 7.0,
      rebounds: 13.2,
      offensiveReb: 3.2,
      defensiveReb: 10.0,
      steals: 0.8,
      blocks: 1.5,
      turnovers: 3.8,
      fieldGoalsMade: 13.2,
      fieldGoalsAttempted: 21.5,
      fieldGoalPct: 61.4,
      threePointsMade: 0.5,
      threePointsAttempted: 2.0,
      threePointPct: 25.0,
      freeThrowsMade: 8.3,
      freeThrowsAttempted: 13.2,
      freeThrowPct: 62.9,
      personalFouls: 3.5,
      plusMinus: 2.3,
      efficiency: 34.5,
    },
  },
  {
    id: 3,
    playerID: "P003",
    teamID: "T003",
    name: "Shai Gilgeous-Alexander",
    team: "Oklahoma City Thunder",
    position: "SG",
    image: "/basketball-player-portrait.png",
    regularSeason: {
      gamesPlayed: 75,
      minutes: 34.0,
      points: 30.1,
      assists: 6.2,
      rebounds: 5.5,
      offensiveReb: 0.9,
      defensiveReb: 4.6,
      steals: 2.0,
      blocks: 0.9,
      turnovers: 2.8,
      fieldGoalsMade: 10.8,
      fieldGoalsAttempted: 20.3,
      fieldGoalPct: 53.2,
      threePointsMade: 1.3,
      threePointsAttempted: 4.2,
      threePointPct: 31.0,
      freeThrowsMade: 7.2,
      freeThrowsAttempted: 8.3,
      freeThrowPct: 86.7,
      personalFouls: 2.3,
      plusMinus: 7.1,
      efficiency: 28.5,
    },
    playoffs: {
      gamesPlayed: 11,
      minutes: 37.2,
      points: 26.8,
      assists: 6.5,
      rebounds: 6.1,
      offensiveReb: 1.0,
      defensiveReb: 5.1,
      steals: 1.5,
      blocks: 1.2,
      turnovers: 3.1,
      fieldGoalsMade: 9.5,
      fieldGoalsAttempted: 19.8,
      fieldGoalPct: 48.0,
      threePointsMade: 1.1,
      threePointsAttempted: 4.5,
      threePointPct: 24.4,
      freeThrowsMade: 6.7,
      freeThrowsAttempted: 7.8,
      freeThrowPct: 85.9,
      personalFouls: 2.8,
      plusMinus: 1.2,
      efficiency: 26.3,
    },
  },
  {
    id: 4,
    playerID: "P004",
    teamID: "T004",
    name: "Nikola Jokić",
    team: "Denver Nuggets",
    position: "C",
    image: "/basketball-player-portrait.png",
    regularSeason: {
      gamesPlayed: 79,
      minutes: 34.6,
      points: 26.4,
      assists: 9.0,
      rebounds: 12.4,
      offensiveReb: 2.9,
      defensiveReb: 9.5,
      steals: 1.4,
      blocks: 0.9,
      turnovers: 3.0,
      fieldGoalsMade: 10.3,
      fieldGoalsAttempted: 17.4,
      fieldGoalPct: 59.2,
      threePointsMade: 1.3,
      threePointsAttempted: 3.7,
      threePointPct: 35.1,
      freeThrowsMade: 4.5,
      freeThrowsAttempted: 5.4,
      freeThrowPct: 83.3,
      personalFouls: 2.7,
      plusMinus: 9.2,
      efficiency: 30.2,
    },
    playoffs: {
      gamesPlayed: 12,
      minutes: 38.5,
      points: 29.2,
      assists: 10.1,
      rebounds: 13.5,
      offensiveReb: 3.1,
      defensiveReb: 10.4,
      steals: 1.2,
      blocks: 1.1,
      turnovers: 3.5,
      fieldGoalsMade: 11.2,
      fieldGoalsAttempted: 18.9,
      fieldGoalPct: 59.3,
      threePointsMade: 1.5,
      threePointsAttempted: 4.1,
      threePointPct: 36.6,
      freeThrowsMade: 5.3,
      freeThrowsAttempted: 6.2,
      freeThrowPct: 85.5,
      personalFouls: 3.0,
      plusMinus: 5.8,
      efficiency: 32.8,
    },
  },
]

export const mockTeams = {
  east: [
    {
      id: 1,
      teamID: "T005",
      name: "Boston Celtics",
      abbreviation: "BOS",
      conference: "Eastern",
      logo: "/boston-celtics-logo.png",
      regularSeason: {
        wins: 64,
        losses: 18,
        winPct: 0.78,
        rank: 1,
        defRatingRank: 2,
        defRebRank: 5,
        stealRank: 8,
        blockRank: 12,
      },
      playoffs: {
        wins: 16,
        losses: 3,
        winPct: 0.842,
        rank: 1,
        defRatingRank: 1,
        defRebRank: 3,
        stealRank: 6,
        blockRank: 10,
      },
      players: [
        {
          id: 5,
          playerID: "P005",
          name: "Jayson Tatum",
          position: "SF",
          image: "/basketball-player-portrait.png",
          regularSeason: {
            gamesPlayed: 74,
            points: 26.9,
            assists: 4.9,
            rebounds: 8.1,
            efficiency: 24.5,
          },
        },
        {
          id: 6,
          playerID: "P006",
          name: "Jaylen Brown",
          position: "SG",
          image: "/basketball-player-portrait.png",
          regularSeason: {
            gamesPlayed: 70,
            points: 23.0,
            assists: 3.6,
            rebounds: 5.5,
            efficiency: 21.2,
          },
        },
      ],
    },
    {
      id: 2,
      teamID: "T002",
      name: "Milwaukee Bucks",
      abbreviation: "MIL",
      conference: "Eastern",
      logo: "/milwaukee-bucks-logo.jpg",
      regularSeason: {
        wins: 49,
        losses: 33,
        winPct: 0.598,
        rank: 2,
        defRatingRank: 15,
        defRebRank: 8,
        stealRank: 12,
        blockRank: 3,
      },
      playoffs: {
        wins: 2,
        losses: 4,
        winPct: 0.333,
        rank: 8,
        defRatingRank: 12,
        defRebRank: 6,
        stealRank: 14,
        blockRank: 5,
      },
      players: [
        {
          id: 2,
          playerID: "P002",
          name: "Giannis Antetokounmpo",
          position: "PF",
          image: "/basketball-player-portrait.png",
          regularSeason: {
            gamesPlayed: 73,
            points: 30.4,
            assists: 6.5,
            rebounds: 11.5,
            efficiency: 32.1,
          },
        },
      ],
    },
    {
      id: 3,
      teamID: "T006",
      name: "Cleveland Cavaliers",
      abbreviation: "CLE",
      conference: "Eastern",
      logo: "/cleveland-cavaliers-logo.png",
      regularSeason: {
        wins: 48,
        losses: 34,
        winPct: 0.585,
        rank: 3,
        defRatingRank: 10,
        defRebRank: 11,
        stealRank: 5,
        blockRank: 15,
      },
      playoffs: {
        wins: 9,
        losses: 6,
        winPct: 0.6,
        rank: 4,
        defRatingRank: 8,
        defRebRank: 9,
        stealRank: 7,
        blockRank: 11,
      },
      players: [],
    },
    {
      id: 4,
      teamID: "T007",
      name: "New York Knicks",
      abbreviation: "NYK",
      conference: "Eastern",
      logo: "/new-york-knicks-logo.png",
      regularSeason: {
        wins: 50,
        losses: 32,
        winPct: 0.61,
        rank: 4,
        defRatingRank: 4,
        defRebRank: 3,
        stealRank: 15,
        blockRank: 8,
      },
      playoffs: {
        wins: 7,
        losses: 6,
        winPct: 0.538,
        rank: 5,
        defRatingRank: 5,
        defRebRank: 4,
        stealRank: 13,
        blockRank: 7,
      },
      players: [],
    },
  ],
  west: [
    {
      id: 1,
      teamID: "T003",
      name: "Oklahoma City Thunder",
      abbreviation: "OKC",
      conference: "Western",
      logo: "/oklahoma-city-thunder-logo.png",
      regularSeason: {
        wins: 57,
        losses: 25,
        winPct: 0.695,
        rank: 1,
        defRatingRank: 3,
        defRebRank: 6,
        stealRank: 1,
        blockRank: 4,
      },
      playoffs: {
        wins: 10,
        losses: 7,
        winPct: 0.588,
        rank: 3,
        defRatingRank: 4,
        defRebRank: 7,
        stealRank: 2,
        blockRank: 6,
      },
      players: [
        {
          id: 3,
          playerID: "P003",
          name: "Shai Gilgeous-Alexander",
          position: "SG",
          image: "/basketball-player-portrait.png",
          regularSeason: {
            gamesPlayed: 75,
            points: 30.1,
            assists: 6.2,
            rebounds: 5.5,
            efficiency: 28.5,
          },
        },
      ],
    },
    {
      id: 2,
      teamID: "T004",
      name: "Denver Nuggets",
      abbreviation: "DEN",
      conference: "Western",
      logo: "/denver-nuggets-logo.jpg",
      regularSeason: {
        wins: 57,
        losses: 25,
        winPct: 0.695,
        rank: 2,
        defRatingRank: 11,
        defRebRank: 9,
        stealRank: 10,
        blockRank: 6,
      },
      playoffs: {
        wins: 5,
        losses: 7,
        winPct: 0.417,
        rank: 6,
        defRatingRank: 9,
        defRebRank: 8,
        stealRank: 11,
        blockRank: 8,
      },
      players: [
        {
          id: 4,
          playerID: "P004",
          name: "Nikola Jokić",
          position: "C",
          image: "/basketball-player-portrait.png",
          regularSeason: {
            gamesPlayed: 79,
            points: 26.4,
            assists: 9.0,
            rebounds: 12.4,
            efficiency: 30.2,
          },
        },
      ],
    },
    {
      id: 3,
      teamID: "T008",
      name: "Minnesota Timberwolves",
      abbreviation: "MIN",
      conference: "Western",
      logo: "/minnesota-timberwolves-logo.png",
      regularSeason: {
        wins: 56,
        losses: 26,
        winPct: 0.683,
        rank: 3,
        defRatingRank: 1,
        defRebRank: 4,
        stealRank: 3,
        blockRank: 1,
      },
      playoffs: {
        wins: 10,
        losses: 7,
        winPct: 0.588,
        rank: 2,
        defRatingRank: 2,
        defRebRank: 5,
        stealRank: 4,
        blockRank: 2,
      },
      players: [],
    },
    {
      id: 4,
      teamID: "T009",
      name: "LA Clippers",
      abbreviation: "LAC",
      conference: "Western",
      logo: "/la-clippers-logo.png",
      regularSeason: {
        wins: 51,
        losses: 31,
        winPct: 0.622,
        rank: 4,
        defRatingRank: 7,
        defRebRank: 12,
        stealRank: 6,
        blockRank: 9,
      },
      playoffs: {
        wins: 2,
        losses: 4,
        winPct: 0.333,
        rank: 7,
        defRatingRank: 10,
        defRebRank: 11,
        stealRank: 9,
        blockRank: 12,
      },
      players: [],
    },
  ],
}

export function getAllTeams() {
  return [...mockTeams.east, ...mockTeams.west]
}

export function getTeamById(id: string) {
  const allTeams = getAllTeams()
  return allTeams.find((team) => team.teamID === id)
}

export function getPlayerById(id: string) {
  return mockPlayers.find((player) => player.playerID === id)
}
